/**
 * DIE WOCHEN-BOTSCHAFTEN DES FUTURE SELF PROGRAM (11.08.2026).
 *
 * Owner, wörtlich: „wir posten trotzdem ein Video am Anfang der Woche. Ich habe das Video
 * für die Erste Woche schon mal produziert. Liegt in dem Ordner und heisst Week1. Wenn
 * jemand das programm kauft, werde ich auch das zweite video produzieren. … Das kann man
 * auch übersetzten. eventuell als text."
 *
 * WARUM DAS VIDEO ENGLISCH BLEIBT UND NUR DER TEXT ÜBERSETZT WIRD: Der Owner spricht selbst
 * vor der Kamera — eine neue Tonspur je Sprache würde vier Produktionen pro Woche bedeuten,
 * für ein Programm mit sieben Sprachen. Genau das meint er mit „eventuell als text": dasselbe
 * Muster wie `unterVideo` auf der Themenseite — ein Beispielvideo wird nicht übersetzt, es
 * wird untertitelt. Das Video bleibt EIN Original, der `zeilen`-Text darunter trägt die
 * Übersetzung in `anzeigeLang` (dieselbe Sprachumschaltung wie der Rest der Programmseite).
 *
 * WARUM ALLES FEHLERTOLERANT SEIN MUSS: `Week1.mp4` legt der Owner erst noch in
 * `public/Versprechen` ab — beim Schreiben dieser Datei lag sie dort noch nicht. Wochen 2–4
 * kommen laut seinem Zitat überhaupt erst, WENN jemand das Programm kauft ("werde ich auch
 * das zweite video produzieren") — sie können monatelang fehlen. Diese Datei selbst bricht
 * deswegen nie: Sie liefert für jede Woche einen Video-Pfad, der vielleicht existiert, und
 * die anzeigende Seite (app/future-program/page.tsx) blendet die Video-Karte aus, sobald das
 * Laden scheitert — der übersetzte Text bleibt in jedem Fall stehen. Kein `fs` hier: Das ist
 * eine reine Text-Datei, client- UND server-tauglich, die nur Pfade und Sätze benennt.
 *
 * ZEILE FÜR ZEILE, wie beim Vorlese-Skript des Versprechens (`lib/versprechen.ts`): Jede
 * Leerzeile in den Owner-Texten trennt einen Gedanken vom nächsten, deshalb wird daraus eine
 * eigene Zeile statt eines Fliesstext-Absatzes — so liest es sich, wie er es spricht.
 *
 * „I'm going to bandit this life." — hier als „Bandit this life." — bleibt in JEDER Sprache
 * unübersetzt Englisch (Markensatz, siehe `VERSPRECHEN_SATZ_EN` in lib/versprechen.ts:
 * „to bandit" gibt es im Englischen nicht als Verb, das Wort gehört uns wie „google it").
 * „Make the promise." und „Keep the promise." werden dagegen übersetzt, wie auf der
 * Landingpage („Mach das Versprechen.").
 *
 * KEINE GELD- ODER ERFOLGSVERSPRECHEN: Diese Zeilen sind wörtlich das, was der Owner
 * eingesprochen hat — nichts hinzuerfunden, nichts verstärkt.
 */

export type ProgramWoche = {
  /** Pfad zur Video-Datei — existiert vielleicht noch nicht (siehe Datei-Kommentar oben). */
  video: string;
  /** Poster-Bild, „aus .mp4 wird .jpg" (Hausregel) — dieselbe Datei-Existenz-Unsicherheit. */
  poster: string;
  titel: Record<string, string>;
  zeilen: Record<string, string[]>;
};

export const PROGRAM_WOCHEN: ProgramWoche[] = [
  {
    video: "/Versprechen/Week1.mp4",
    poster: "/Versprechen/Week1.jpg",
    titel: {
      en: "Week One — Clarity",
      de: "Woche eins — Klarheit",
      ro: "Săptămâna unu — Claritate",
      es: "Semana uno — Claridad",
      fr: "Semaine un — Clarté",
      pt: "Semana um — Clareza",
      it: "Settimana uno — Chiarezza",
    },
    zeilen: {
      en: [
        "Welcome to Week One.",
        "Before you change anything, you need to know where you're going.",
        "This week is about clarity.",
        "What do you really want?",
        "What matters enough to work for?",
        "And what kind of life do you want to wake up to five years from now?",
        "Don't try to solve everything yet.",
        "Just get honest about the direction.",
        "Your future starts with knowing where you're going.",
        "Make the promise.",
        "Then give it a direction.",
      ],
      de: [
        "Willkommen in Woche eins.",
        "Bevor du etwas veränderst, musst du wissen, wohin du willst.",
        "Diese Woche geht es um Klarheit.",
        "Was willst du wirklich?",
        "Was ist dir wichtig genug, um dafür zu arbeiten?",
        "Und in welchem Leben willst du in fünf Jahren aufwachen?",
        "Versuch noch nicht, alles zu lösen.",
        "Werd einfach ehrlich über die Richtung.",
        "Deine Zukunft beginnt damit, dass du weisst, wohin du willst.",
        "Mach das Versprechen.",
        "Und gib ihm eine Richtung.",
      ],
      ro: [
        "Bine ai venit în Săptămâna unu.",
        "Înainte să schimbi ceva, trebuie să știi încotro te îndrepți.",
        "Săptămâna asta e despre claritate.",
        "Ce îți dorești cu adevărat?",
        "Ce contează suficient de mult încât să muncești pentru el?",
        "Și în ce fel de viață vrei să te trezești peste cinci ani?",
        "Nu încerca încă să rezolvi totul.",
        "Fii pur și simplu sincer în privința direcției.",
        "Viitorul tău începe cu faptul că știi încotro te îndrepți.",
        "Fă promisiunea.",
        "Apoi dă-i o direcție.",
      ],
      es: [
        "Bienvenido a la Semana uno.",
        "Antes de cambiar nada, necesitas saber hacia dónde vas.",
        "Esta semana trata sobre claridad.",
        "¿Qué es lo que realmente quieres?",
        "¿Qué te importa lo suficiente como para trabajar por ello?",
        "¿Y en qué tipo de vida quieres despertar dentro de cinco años?",
        "Todavía no intentes resolverlo todo.",
        "Sé honesto sobre la dirección.",
        "Tu futuro empieza sabiendo hacia dónde vas.",
        "Haz la promesa.",
        "Y dale una dirección.",
      ],
      fr: [
        "Bienvenue dans la Semaine un.",
        "Avant de changer quoi que ce soit, tu dois savoir où tu vas.",
        "Cette semaine, c'est la clarté.",
        "Que veux-tu vraiment ?",
        "Qu'est-ce qui compte assez pour que tu travailles pour ça ?",
        "Et dans quelle vie veux-tu te réveiller dans cinq ans ?",
        "N'essaie pas encore de tout résoudre.",
        "Sois simplement honnête sur la direction.",
        "Ton avenir commence quand tu sais où tu vas.",
        "Fais la promesse.",
        "Puis donne-lui une direction.",
      ],
      pt: [
        "Bem-vindo à Semana um.",
        "Antes de mudares seja o que for, precisas de saber para onde vais.",
        "Esta semana é sobre clareza.",
        "O que é que tu realmente queres?",
        "O que é que importa o suficiente para trabalhares por isso?",
        "E em que tipo de vida queres acordar daqui a cinco anos?",
        "Ainda não tentes resolver tudo.",
        "Sê apenas honesto sobre a direção.",
        "O teu futuro começa por saberes para onde vais.",
        "Faz a promessa.",
        "Depois dá-lhe uma direção.",
      ],
      it: [
        "Benvenuto nella Settimana uno.",
        "Prima di cambiare qualcosa, devi sapere dove stai andando.",
        "Questa settimana parla di chiarezza.",
        "Cosa vuoi davvero?",
        "Cosa conta abbastanza da lavorarci per ottenerlo?",
        "E in che tipo di vita vuoi svegliarti tra cinque anni?",
        "Non cercare ancora di risolvere tutto.",
        "Sii semplicemente onesto sulla direzione.",
        "Il tuo futuro inizia sapendo dove stai andando.",
        "Fai la promessa.",
        "E dalle una direzione.",
      ],
    },
  },
  {
    video: "/Versprechen/Week2.mp4",
    poster: "/Versprechen/Week2.jpg",
    titel: {
      en: "Week Two — Action",
      de: "Woche zwei — Handeln",
      ro: "Săptămâna doi — Acțiune",
      es: "Semana dos — Acción",
      fr: "Semaine deux — Action",
      pt: "Semana dois — Ação",
      it: "Settimana due — Azione",
    },
    zeilen: {
      en: [
        "Welcome to Week Two.",
        "Now it's time to move.",
        "You don't need the perfect plan.",
        "You don't need to know every step between here and five years from now.",
        "You need one real step.",
        "Something you can do today.",
        "Then another tomorrow.",
        "Big changes are built from small actions repeated over time.",
        "Stop waiting for the perfect moment.",
        "Take the next step.",
      ],
      de: [
        "Willkommen in Woche zwei.",
        "Jetzt ist es Zeit, in Bewegung zu kommen.",
        "Du brauchst nicht den perfekten Plan.",
        "Du musst nicht jeden Schritt von hier bis in fünf Jahre kennen.",
        "Du brauchst einen echten Schritt.",
        "Etwas, das du heute tun kannst.",
        "Und morgen einen weiteren.",
        "Grosse Veränderungen entstehen aus kleinen Handlungen, die man immer wieder tut.",
        "Hör auf, auf den perfekten Moment zu warten.",
        "Mach den nächsten Schritt.",
      ],
      ro: [
        "Bine ai venit în Săptămâna doi.",
        "Acum e timpul să te miști.",
        "Nu ai nevoie de planul perfect.",
        "Nu trebuie să cunoști fiecare pas de aici până peste cinci ani.",
        "Ai nevoie de un singur pas real.",
        "Ceva ce poți face azi.",
        "Apoi altceva mâine.",
        "Schimbările mari se construiesc din acțiuni mici repetate în timp.",
        "Nu mai aștepta momentul perfect.",
        "Fă următorul pas.",
      ],
      es: [
        "Bienvenido a la Semana dos.",
        "Ahora es momento de moverse.",
        "No necesitas el plan perfecto.",
        "No necesitas conocer cada paso de aquí a dentro de cinco años.",
        "Necesitas un paso real.",
        "Algo que puedas hacer hoy.",
        "Y otro mañana.",
        "Los grandes cambios se construyen con pequeñas acciones repetidas en el tiempo.",
        "Deja de esperar el momento perfecto.",
        "Da el siguiente paso.",
      ],
      fr: [
        "Bienvenue dans la Semaine deux.",
        "Il est temps de bouger.",
        "Tu n'as pas besoin du plan parfait.",
        "Tu n'as pas besoin de connaître chaque étape entre maintenant et dans cinq ans.",
        "Tu as besoin d'une vraie étape.",
        "Quelque chose que tu peux faire aujourd'hui.",
        "Puis une autre demain.",
        "Les grands changements naissent de petites actions répétées dans le temps.",
        "Arrête d'attendre le moment parfait.",
        "Fais le pas suivant.",
      ],
      pt: [
        "Bem-vindo à Semana dois.",
        "Agora é hora de te mexeres.",
        "Não precisas do plano perfeito.",
        "Não precisas de conhecer cada passo daqui até daqui a cinco anos.",
        "Precisas de um passo real.",
        "Algo que possas fazer hoje.",
        "E outro amanhã.",
        "As grandes mudanças constroem-se com pequenas ações repetidas ao longo do tempo.",
        "Para de esperar pelo momento perfeito.",
        "Dá o próximo passo.",
      ],
      it: [
        "Benvenuto nella Settimana due.",
        "Ora è il momento di muoversi.",
        "Non hai bisogno del piano perfetto.",
        "Non devi conoscere ogni passo da qui a tra cinque anni.",
        "Hai bisogno di un passo vero.",
        "Qualcosa che puoi fare oggi.",
        "E un altro domani.",
        "I grandi cambiamenti nascono da piccole azioni ripetute nel tempo.",
        "Smetti di aspettare il momento perfetto.",
        "Fai il prossimo passo.",
      ],
    },
  },
  {
    video: "/Versprechen/Week3.mp4",
    poster: "/Versprechen/Week3.jpg",
    titel: {
      en: "Week Three — Consistency",
      de: "Woche drei — Beständigkeit",
      ro: "Săptămâna trei — Consecvență",
      es: "Semana tres — Constancia",
      fr: "Semaine trois — Constance",
      pt: "Semana três — Constância",
      it: "Settimana tre — Costanza",
    },
    zeilen: {
      en: [
        "Welcome to Week Three.",
        "Starting is easy.",
        "Continuing is what changes you.",
        "There will be days when you feel motivated.",
        "And there will be days when you don't.",
        "Do it anyway.",
        "One small action.",
        "Then repeat it.",
        "You don't need to transform your life in one day.",
        "You need to become the person who keeps showing up.",
        "Keep the promise.",
      ],
      de: [
        "Willkommen in Woche drei.",
        "Anfangen ist leicht.",
        "Weitermachen ist es, was dich verändert.",
        "Es wird Tage geben, an denen du motiviert bist.",
        "Und es wird Tage geben, an denen du es nicht bist.",
        "Mach es trotzdem.",
        "Eine kleine Handlung.",
        "Und dann wiederhol sie.",
        "Du musst dein Leben nicht an einem Tag verwandeln.",
        "Du musst der Mensch werden, der immer wieder erscheint.",
        "Halte das Versprechen.",
      ],
      ro: [
        "Bine ai venit în Săptămâna trei.",
        "A începe e ușor.",
        "A continua e ceea ce te schimbă.",
        "Vor fi zile în care te vei simți motivat.",
        "Și vor fi zile în care nu.",
        "Fă-o oricum.",
        "O mică acțiune.",
        "Apoi repet-o.",
        "Nu trebuie să-ți transformi viața într-o singură zi.",
        "Trebuie să devii persoana care continuă să apară.",
        "Ține-ți promisiunea.",
      ],
      es: [
        "Bienvenido a la Semana tres.",
        "Empezar es fácil.",
        "Continuar es lo que te cambia.",
        "Habrá días en que te sientas motivado.",
        "Y habrá días en que no.",
        "Hazlo de todos modos.",
        "Una pequeña acción.",
        "Y luego repítela.",
        "No necesitas transformar tu vida en un día.",
        "Necesitas convertirte en la persona que sigue apareciendo.",
        "Cumple la promesa.",
      ],
      fr: [
        "Bienvenue dans la Semaine trois.",
        "Commencer, c'est facile.",
        "C'est continuer qui te change.",
        "Il y aura des jours où tu te sentiras motivé.",
        "Et des jours où tu ne le seras pas.",
        "Fais-le quand même.",
        "Une petite action.",
        "Puis répète-la.",
        "Tu n'as pas besoin de transformer ta vie en un jour.",
        "Tu dois devenir la personne qui continue de se présenter.",
        "Tiens la promesse.",
      ],
      pt: [
        "Bem-vindo à Semana três.",
        "Começar é fácil.",
        "Continuar é o que te muda.",
        "Vai haver dias em que te sentes motivado.",
        "E vai haver dias em que não.",
        "Faz na mesma.",
        "Uma pequena ação.",
        "Depois repete-a.",
        "Não precisas de transformar a tua vida num dia.",
        "Precisas de te tornares na pessoa que continua a aparecer.",
        "Cumpre a promessa.",
      ],
      it: [
        "Benvenuto nella Settimana tre.",
        "Iniziare è facile.",
        "È continuare che ti cambia.",
        "Ci saranno giorni in cui ti sentirai motivato.",
        "E ci saranno giorni in cui no.",
        "Fallo comunque.",
        "Una piccola azione.",
        "Poi ripetila.",
        "Non devi trasformare la tua vita in un giorno.",
        "Devi diventare la persona che continua a presentarsi.",
        "Mantieni la promessa.",
      ],
    },
  },
  {
    video: "/Versprechen/Week4.mp4",
    poster: "/Versprechen/Week4.jpg",
    titel: {
      en: "Week Four — Direction",
      de: "Woche vier — Richtung",
      ro: "Săptămâna patru — Direcție",
      es: "Semana cuatro — Dirección",
      fr: "Semaine quatre — Direction",
      pt: "Semana quatro — Direção",
      it: "Settimana quattro — Direzione",
    },
    zeilen: {
      en: [
        "Welcome to Week Four.",
        "Thirty days won't build your entire future.",
        "But they can prove something important.",
        "That you can choose a direction.",
        "Take action.",
        "Build consistency.",
        "And keep going when the excitement is gone.",
        "Now decide what comes next.",
        "Keep what works.",
        "Remove what doesn't.",
        "And give the next ninety days a clear purpose.",
        "This isn't the finish line.",
        "Bandit this life.",
        "You made a promise.",
        "Keep it.",
      ],
      de: [
        "Willkommen in Woche vier.",
        "Dreissig Tage bauen nicht deine ganze Zukunft.",
        "Aber sie können etwas Wichtiges beweisen.",
        "Dass du eine Richtung wählen kannst.",
        "Handeln.",
        "Beständigkeit aufbauen.",
        "Und weitermachen, wenn die Begeisterung weg ist.",
        "Jetzt entscheide, was als Nächstes kommt.",
        "Behalte, was funktioniert.",
        "Streich, was nicht funktioniert.",
        "Und gib den nächsten neunzig Tagen einen klaren Zweck.",
        "Das ist nicht die Ziellinie.",
        "Bandit this life.",
        "Du hast ein Versprechen gemacht.",
        "Halt es.",
      ],
      ro: [
        "Bine ai venit în Săptămâna patru.",
        "Treizeci de zile nu îți construiesc întregul viitor.",
        "Dar pot dovedi ceva important.",
        "Că poți alege o direcție.",
        "Acționezi.",
        "Construiești consecvență.",
        "Și continui chiar și atunci când entuziasmul dispare.",
        "Acum decide ce urmează.",
        "Păstrează ce funcționează.",
        "Elimină ce nu funcționează.",
        "Și dă următoarelor nouăzeci de zile un scop clar.",
        "Aceasta nu e linia de sosire.",
        "Bandit this life.",
        "Ai făcut o promisiune.",
        "Ține-te de ea.",
      ],
      es: [
        "Bienvenido a la Semana cuatro.",
        "Treinta días no construyen todo tu futuro.",
        "Pero pueden demostrar algo importante.",
        "Que puedes elegir una dirección.",
        "Actuar.",
        "Construir constancia.",
        "Y seguir cuando la emoción se ha ido.",
        "Ahora decide qué viene después.",
        "Conserva lo que funciona.",
        "Elimina lo que no funciona.",
        "Y dale a los próximos noventa días un propósito claro.",
        "Esto no es la meta.",
        "Bandit this life.",
        "Hiciste una promesa.",
        "Cúmplela.",
      ],
      fr: [
        "Bienvenue dans la Semaine quatre.",
        "Trente jours ne construisent pas tout ton avenir.",
        "Mais ils peuvent prouver quelque chose d'important.",
        "Que tu peux choisir une direction.",
        "Passer à l'action.",
        "Construire de la constance.",
        "Et continuer quand l'enthousiasme est parti.",
        "Décide maintenant ce qui vient ensuite.",
        "Garde ce qui marche.",
        "Enlève ce qui ne marche pas.",
        "Et donne aux quatre-vingt-dix prochains jours un but clair.",
        "Ce n'est pas la ligne d'arrivée.",
        "Bandit this life.",
        "Tu as fait une promesse.",
        "Tiens-la.",
      ],
      pt: [
        "Bem-vindo à Semana quatro.",
        "Trinta dias não constroem todo o teu futuro.",
        "Mas podem provar algo importante.",
        "Que consegues escolher uma direção.",
        "Agir.",
        "Construir consistência.",
        "E continuar quando o entusiasmo já foi.",
        "Agora decide o que vem a seguir.",
        "Mantém o que funciona.",
        "Remove o que não funciona.",
        "E dá aos próximos noventa dias um propósito claro.",
        "Isto não é a linha de chegada.",
        "Bandit this life.",
        "Fizeste uma promessa.",
        "Cumpre-a.",
      ],
      it: [
        "Benvenuto nella Settimana quattro.",
        "Trenta giorni non costruiscono tutto il tuo futuro.",
        "Ma possono dimostrare qualcosa di importante.",
        "Che puoi scegliere una direzione.",
        "Agire.",
        "Costruire costanza.",
        "E continuare quando l'entusiasmo se n'è andato.",
        "Ora decidi cosa viene dopo.",
        "Tieni ciò che funziona.",
        "Rimuovi ciò che non funziona.",
        "E dai ai prossimi novanta giorni uno scopo chiaro.",
        "Questo non è il traguardo.",
        "Bandit this life.",
        "Hai fatto una promessa.",
        "Mantienila.",
      ],
    },
  },
];

/** Tag 1–7 → Woche 1, 8–14 → Woche 2, 15–21 → Woche 3, 22–30 → Woche 4. */
export function programWoche(tag: number): { nr: 1 | 2 | 3 | 4; woche: ProgramWoche } {
  const nr = (tag <= 7 ? 1 : tag <= 14 ? 2 : tag <= 21 ? 3 : 4) as 1 | 2 | 3 | 4;
  return { nr, woche: PROGRAM_WOCHEN[nr - 1] };
}
