import { isLang, type Lang } from "@/lib/lang";

/**
 * DIE TEXTE DES PORTALS LAKATOSBANDI.COM — Englisch zuerst, dann Rumänisch, dann Deutsch (Owner
 * 10.09.2026: „alles muss mit Englisch anfangen").
 *
 * FEST GESCHRIEBEN, NICHT ÜBERSETZT: Es sind wenige kurze Zeilen, und das Portal ist die erste
 * Seite, die ein Käufer sieht — ein Übersetzungsaufruf beim ersten Laden kostet dort Sekunden.
 */
export const PORTAL_SPRACHEN: Lang[] = ["en", "ro", "de"];

const TEXTE = {
  en: {
    unter: "Marketing for Art",
    titel: "Discover art — and why it is special.",
    lead: "Selected artists. Every work comes with the sentence that explains what makes it rare. Interested? Talk to the artist's agent.",
    leer: "The first artists are being reviewed right now. Come back soon.",
    anmelden: "Artist login",
    /* Nur auf dem Handy, damit das Logo „lakatosbandi.com" nicht mehr Platz braucht, als der Kopf hat (Owner 11.09.2026). */
    anmeldenKurz: "Login",
    fuerKuenstler: "Are you an artist?",
    fuerKuenstlerText: "Show us your work — we find the buyers who value it.",
    fuerKuenstlerKnopf: "Start for free",
    agent: "Interested in my art? Talk to my agent.",
    werke: "Works",
    pruefung: "This artist is being reviewed and will be online soon.",
    nichtGefunden: "This page doesn't exist (anymore).",
    zurStart: "Go to the start page",
    bearbeitenHinweis: "You are editing your page. Tap a text or an image to change it.",
    bearbeitenPruefung: "Your page is being reviewed — only you can see it for now. Tap a text or an image to change it.",
    ansehen: "See it as buyers do",
    fotoPlatzhalter: "Your photo",
    namePlatzhalter: "Your artist name",
    ortPlatzhalter: "Where you work",
    ueberMichPlatzhalter: "Tell buyers about yourself and your art …",
    spruchPlatzhalter: "Write a line for this work",
    titelPlatzhalter: "Title",
    technikPlatzhalter: "Technique",
    groessePlatzhalter: "Size",
    jahrPlatzhalter: "Year",
    bildTauschen: "Change image",
    bildHinzufuegen: "+ Add a work",
    entfernen: "Remove",
    speichern: "Save",
    gespeichert: "Saved",
    speichernFehler: "That didn't work. Please try again.",
    bildPruefung: "Thanks — we'll take a quick look at this image.",
    bildAbgelehnt: "We can't use this image.",
    loeschenTitel: "Delete your page?",
    loeschenText: "Your page, your works, your lines and all inquiries — permanently. There is no way back.",
    loeschenKnopf: "Delete page",
    loeschenSicher: "Yes, delete permanently",
    loeschenLaeuft: "One moment …",
    loeschenFertig: "Everything is deleted.",
    loeschenFertigText: "Your page and all your data are gone.",
    loeschenFehler: "That didn't work. Please try again.",
    loeschenOhneLink: "This link is not valid (anymore).",
    /* Sein Agent auf seiner Seite (Owner 11.09.2026: „begrüsst den Besucher und fragt: Gefällt dir die Kunst?"). {name} setzt der Code ein. */
    agentTitel: "Agent",
    agentHallo: "Hi! I'm {name}'s agent.",
    agentFrage: "Do you like {name}'s art?",
    /* Der verkaufende Agent (Owner 11.09.2026: „willst du mehr erfahren? — Ja, mich interessiert dieses Kunstwerk"). */
    agentMehrFrage: "Would you like to know more?",
    agentJa: "Yes, I'm interested in this work",
    agentNein: "Just looking",
    agentPreis: "You agree on the price directly with {name}.",
    geschichtePlatzhalter: "The story of this work: where it was made, what's behind it (optional — only your agent reads it)",
    agentBesserHinweis: "The more you tell your agent, the better it sells.",
    preisPlatzhalter: "Price, e.g. 800",
    detaliiPlatzhalter: "Other details, e.g. signed print, edition 3/50",
    preisZeigen: "Show price on my page",
    preisWort: "Price",
    preisAufAnfrage: "Price on request",
    alleWerkeVon: "All works by {name}",
    weitereWerke: "More works",
    agentJaText: "Wonderful! Leave me your name and phone number — {name} will call you personally.",
    agentFeldName: "Name",
    agentFeldTelefon: "Phone",
    agentSenden: "Send",
    agentDatenschutz: "Your details go only to {name}.",
    agentDatenschutzLink: "Privacy",
    agentDanke: "Thank you! {name} will be in touch soon.",
    agentFehler: "That didn't work. Please try again.",
    agentNeinText: "Thanks for looking. Maybe another work speaks to you.",
    loginTitel: "Artist login",
    loginText: "Enter the email address you signed up with. We send you a link to your dashboard — no password needed.",
    loginFeld: "Your email address",
    loginKnopf: "Send me the link",
    loginGesendet: "If there is an artist account for this address, the link is on its way. Check your inbox.",
    loginFehler: "That did not work. Please try again.",
    /* Kein „bald" mehr (Owner 11.09.2026: „jetzt sind wir soweit für Werbung und Marketing"). */
    baldKicker: "For artists",
    /* Owner 10.09.2026: „Das ist eine Marketingplattform für Künstler" — kein Kunst-Zuhause, keine Galerie. */
    baldTitel: "The marketing platform for artists.",
    baldLead: "We turn your work into ads that make people stop: for every piece, the sentence that explains what makes it rare — and an agent that talks to buyers for you. We are selecting our first artists now.",
    baldKnopf: "Apply as an artist",
    /* Sofort online, ein Bild reicht (Owner 11.09.2026) — vorher „drei Werke im selben Stil · Prüfung in 3 Tagen". */
    baldFein: "Free · your page is online right away",
    ersteKuenstler: "First artists",
  },
  ro: {
    unter: "Marketing for Art",
    titel: "Descoperă artă — și de ce este specială.",
    lead: "Artiști selectați. Fiecare lucrare vine cu fraza care spune ce o face rară. Te interesează? Vorbește cu agentul artistului.",
    leer: "Primii artiști sunt verificați chiar acum. Revino în curând.",
    anmelden: "Autentificare artist",
    anmeldenKurz: "Autentificare",
    fuerKuenstler: "Ești artist?",
    fuerKuenstlerText: "Arată-ne lucrările tale — găsim cumpărătorii care le apreciază.",
    fuerKuenstlerKnopf: "Începe gratuit",
    agent: "Te interesează arta mea? Vorbește cu agentul meu.",
    werke: "Lucrări",
    pruefung: "Acest artist este în verificare și va fi online în curând.",
    nichtGefunden: "Această pagină nu există (sau nu mai există).",
    zurStart: "Mergi la pagina de start",
    bearbeitenHinweis: "Îți editezi pagina. Alege un text sau o imagine ca să le schimbi.",
    bearbeitenPruefung: "Pagina ta este în verificare — deocamdată doar tu o vezi. Alege un text sau o imagine ca să le schimbi.",
    ansehen: "Vezi-o cum o văd cumpărătorii",
    fotoPlatzhalter: "Fotografia ta",
    namePlatzhalter: "Numele tău de artist",
    ortPlatzhalter: "Unde lucrezi",
    ueberMichPlatzhalter: "Spune-le cumpărătorilor despre tine și arta ta …",
    spruchPlatzhalter: "Scrie o frază pentru această lucrare",
    titelPlatzhalter: "Titlu",
    technikPlatzhalter: "Tehnică",
    groessePlatzhalter: "Dimensiune",
    jahrPlatzhalter: "An",
    bildTauschen: "Schimbă imaginea",
    bildHinzufuegen: "+ Adaugă o lucrare",
    /* Owner 11.09.2026: „Șterge, nu elimină". */
    entfernen: "Șterge",
    speichern: "Salvează",
    gespeichert: "Salvat",
    speichernFehler: "Nu a mers. Te rog încearcă din nou.",
    bildPruefung: "Mulțumim — ne uităm puțin la această imagine.",
    bildAbgelehnt: "Nu putem folosi această imagine.",
    loeschenTitel: "Îți ștergi pagina?",
    loeschenText: "Pagina ta, lucrările tale, frazele și toate cererile — definitiv. Nu există cale de întoarcere.",
    loeschenKnopf: "Șterge pagina",
    loeschenSicher: "Da, șterge definitiv",
    loeschenLaeuft: "Un moment …",
    loeschenFertig: "Totul a fost șters.",
    loeschenFertigText: "Pagina ta și toate datele tale au dispărut.",
    loeschenFehler: "Nu a mers. Te rog încearcă din nou.",
    loeschenOhneLink: "Acest link nu este (mai) valid.",
    agentTitel: "Agent",
    agentHallo: "Bună! Sunt agentul lui {name}.",
    /* Owner 11.09.2026: „Îți place arta (statt: Îți place arta lui {Name})". */
    agentFrage: "Îți place arta lui {name}?",
    agentMehrFrage: "Vrei să afli mai multe?",
    agentJa: "Da, mă interesează această lucrare",
    agentNein: "Doar mă uit",
    agentPreis: "Prețul îl stabilești direct cu {name}.",
    geschichtePlatzhalter: "Povestea lucrării: unde a luat naștere, ce e în spatele ei (opțional — o citește doar agentul tău)",
    agentBesserHinweis: "Cu cât îi spui mai mult agentului tău, cu atât vinde mai bine.",
    preisPlatzhalter: "Preț, ex.: 800",
    detaliiPlatzhalter: "Alte detalii, ex.: print semnat, ediție 3/50",
    preisZeigen: "Arată prețul pe pagina mea",
    preisWort: "Preț",
    preisAufAnfrage: "Preț la cerere",
    alleWerkeVon: "Toate lucrările lui {name}",
    weitereWerke: "Alte lucrări",
    agentJaText: "Minunat! Lasă-mi numele și telefonul — {name} te sună personal.",
    agentFeldName: "Nume",
    agentFeldTelefon: "Telefon",
    agentSenden: "Trimite",
    agentDatenschutz: "Datele tale ajung doar la {name}.",
    agentDatenschutzLink: "Confidențialitate",
    agentDanke: "Mulțumesc! {name} te contactează în curând.",
    agentFehler: "Nu a mers. Te rog încearcă din nou.",
    agentNeinText: "Mulțumesc că ai privit. Poate altă lucrare îți vorbește.",
    loginTitel: "Autentificare artist",
    loginText: "Scrie adresa de e-mail cu care te-ai înscris. Îți trimitem un link către dashboard — fără parolă.",
    loginFeld: "Adresa ta de e-mail",
    loginKnopf: "Trimite-mi linkul",
    loginGesendet: "Dacă există un cont de artist pentru această adresă, linkul este pe drum. Verifică-ți e-mailul.",
    loginFehler: "Nu a mers. Te rugăm să încerci din nou.",
    baldKicker: "Pentru artiști",
    baldTitel: "Platforma de marketing pentru artiști.",
    baldLead: "Transformăm lucrările tale în reclame care îi fac pe oameni să se oprească: pentru fiecare lucrare, fraza care spune ce o face rară — și un agent care vorbește cu cumpărătorii pentru tine. Acum ne alegem primii artiști.",
    baldKnopf: "Aplică ca artist",
    baldFein: "Gratuit · pagina ta e online imediat",
    ersteKuenstler: "Primii artiști",
  },
  de: {
    unter: "Marketing for Art",
    titel: "Entdecke Kunst — und warum sie besonders ist.",
    lead: "Ausgewählte Künstler. Zu jedem Werk steht der Satz, der sagt, was es selten macht. Interessiert? Sprich mit dem Agenten des Künstlers.",
    leer: "Die ersten Künstler werden gerade geprüft. Schau bald wieder vorbei.",
    anmelden: "Login für Künstler",
    anmeldenKurz: "Login",
    fuerKuenstler: "Bist du Künstler?",
    fuerKuenstlerText: "Zeig uns deine Werke — wir finden die Käufer, die sie schätzen.",
    fuerKuenstlerKnopf: "Kostenlos starten",
    agent: "Interessiert an meiner Kunst? Sprich mit meinem Agenten.",
    werke: "Werke",
    pruefung: "Dieser Künstler wird gerade geprüft und ist bald online.",
    nichtGefunden: "Diese Seite gibt es nicht (mehr).",
    zurStart: "Zur Startseite",
    bearbeitenHinweis: "Du bearbeitest deine Seite. Tippe auf einen Text oder ein Bild, um es zu ändern.",
    bearbeitenPruefung: "Deine Seite wird gerade geprüft — nur du siehst sie. Tippe auf einen Text oder ein Bild, um es zu ändern.",
    ansehen: "So sehen Käufer deine Seite",
    fotoPlatzhalter: "Dein Foto",
    namePlatzhalter: "Dein Künstlername",
    ortPlatzhalter: "Wo du arbeitest",
    ueberMichPlatzhalter: "Erzähl Käufern etwas über dich und deine Kunst …",
    spruchPlatzhalter: "Schreib einen Spruch zu diesem Werk",
    titelPlatzhalter: "Titel",
    technikPlatzhalter: "Technik",
    groessePlatzhalter: "Größe",
    jahrPlatzhalter: "Jahr",
    bildTauschen: "Bild tauschen",
    bildHinzufuegen: "+ Werk hinzufügen",
    entfernen: "Entfernen",
    speichern: "Speichern",
    gespeichert: "Gespeichert",
    speichernFehler: "Das hat nicht geklappt. Versuch es bitte noch einmal.",
    bildPruefung: "Danke — wir sehen uns dieses Bild kurz an.",
    bildAbgelehnt: "Dieses Bild können wir nicht verwenden.",
    loeschenTitel: "Deine Seite löschen?",
    loeschenText: "Deine Seite, deine Werke, deine Sprüche und alle Anfragen — endgültig, ohne Weg zurück.",
    loeschenKnopf: "Seite löschen",
    loeschenSicher: "Ja, endgültig löschen",
    loeschenLaeuft: "Einen Moment …",
    loeschenFertig: "Alles gelöscht.",
    loeschenFertigText: "Deine Seite und alle deine Daten sind weg.",
    loeschenFehler: "Das hat nicht geklappt. Versuch es bitte noch einmal.",
    loeschenOhneLink: "Dieser Link ist nicht (mehr) gültig.",
    agentTitel: "Agent",
    agentHallo: "Hallo! Ich bin der Agent von {name}.",
    agentFrage: "Gefällt dir die Kunst von {name}?",
    agentMehrFrage: "Möchtest du mehr erfahren?",
    agentJa: "Ja, mich interessiert dieses Werk",
    agentNein: "Ich schaue nur",
    agentPreis: "Den Preis besprichst du direkt mit {name}.",
    geschichtePlatzhalter: "Die Geschichte dieses Werks: wo es entstand, was dahintersteht (freiwillig — nur dein Agent liest sie)",
    agentBesserHinweis: "Je mehr du deinem Agenten erzählst, desto besser verkauft er.",
    preisPlatzhalter: "Preis, z. B. 800",
    detaliiPlatzhalter: "Weitere Details, z. B. signierter Druck, Auflage 3/50",
    preisZeigen: "Preis auf meiner Seite zeigen",
    preisWort: "Preis",
    preisAufAnfrage: "Preis auf Anfrage",
    alleWerkeVon: "Alle Werke von {name}",
    weitereWerke: "Weitere Werke",
    agentJaText: "Schön! Hinterlass mir deinen Namen und deine Telefonnummer — {name} ruft dich persönlich an.",
    agentFeldName: "Name",
    agentFeldTelefon: "Telefon",
    agentSenden: "Senden",
    agentDatenschutz: "Deine Angaben gehen nur an {name}.",
    agentDatenschutzLink: "Datenschutz",
    agentDanke: "Danke! {name} meldet sich bald bei dir.",
    agentFehler: "Das hat nicht geklappt. Versuch es bitte noch einmal.",
    agentNeinText: "Danke fürs Anschauen. Vielleicht spricht dich ein anderes Werk an.",
    loginTitel: "Login für Künstler",
    loginText: "Gib die E-Mail-Adresse ein, mit der du dich angemeldet hast. Wir schicken dir einen Link zu deinem Dashboard — ohne Passwort.",
    loginFeld: "Deine E-Mail-Adresse",
    loginKnopf: "Link schicken",
    loginGesendet: "Wenn es für diese Adresse ein Künstlerkonto gibt, ist der Link unterwegs. Schau in dein Postfach.",
    loginFehler: "Das hat nicht geklappt. Bitte versuch es noch einmal.",
    baldKicker: "Für Künstler",
    baldTitel: "Die Marketing-Plattform für Künstler.",
    baldLead: "Wir machen aus deinen Werken Werbung, bei der Menschen anhalten: zu jedem Werk der Satz, der sagt, was es selten macht — und ein Agent, der für dich mit Käufern spricht. Gerade wählen wir die ersten Künstler aus.",
    baldKnopf: "Als Künstler bewerben",
    baldFein: "Kostenlos · deine Seite ist sofort online",
    ersteKuenstler: "Die ersten Künstler",
  },
} as const;

export type PortalTexte = { -readonly [K in keyof typeof TEXTE.en]: string };

export function portalSprache(wunsch?: string | null, rueckfall = "en"): Lang {
  const w = String(wunsch ?? "").slice(0, 2).toLowerCase();
  if (isLang(w) && PORTAL_SPRACHEN.includes(w)) return w;
  const r = String(rueckfall).slice(0, 2).toLowerCase();
  return isLang(r) && PORTAL_SPRACHEN.includes(r) ? r : "en";
}

export const portalTexte = (lang: Lang): PortalTexte => (TEXTE as Record<string, PortalTexte>)[lang] ?? TEXTE.en;
