import type { VersusForgeTexte } from "@/lib/versusforge-texte";

/**
 * EIGENE FASSUNGEN STATT ÜBERSETZUNG (Owner 08.09.2026: „RO und EN nicht wörtlich aus dem
 * Deutschen übersetzen").
 *
 * Das Haus übersetzt jede Textdatei automatisch aus dem Deutschen. Für Erklärtexte reicht
 * das; für die Sätze, die VERKAUFEN, reicht es nicht — eine wörtliche Übersetzung trägt den
 * deutschen Satzbau mit, und der klingt in beiden Sprachen nach Übersetzung. Heute mehrfach
 * gesehen: „Niciunul OLX", „prima închiriere din mai".
 *
 * WAS HIER STEHT, GEWINNT. Was hier fehlt, übersetzt die Maschine weiter — deshalb ist die
 * Tabelle absichtlich kurz und deckt nur den Hero, das Dashboard und die Beispiele ab.
 *
 * RUMÄNISCH IST EIN VORSCHLAG, KEINE ENDFASSUNG. Ich schreibe es so gut ich kann; wirklich
 * natürliches Rumänisch kann nur jemand hineinschreiben, der es spricht. Wer hier korrigiert,
 * korrigiert einmal — danach steht es fest und läuft nie wieder durch die Maschine.
 */
export const EIGEN: Partial<Record<string, Partial<VersusForgeTexte>>> = {
  en: {
    hookFrage: "Your website is live and nothing comes in.",
    hookFrage2: "Here it starts with the ad — everything behind it grows out of that.",
    hookText: "VersusForge writes the ad, runs it, builds the page behind it — and shows you in one dashboard who got in touch.",
    hookKnopf: "Start now",
    argTitel: "Built front to back, not back to front",
    argEins: "Most people build a site or a shop first — months before the first customer shows up.",
    argZwei: "Then comes the moment: damn, now I have to advertise it as well.",
    argDrei: "Here the ad comes first. Everything behind it grows out of that — and replaces your portal.",
    argVier: "The ad is made here too — out of what you actually offer, not from a template.",
    bwHinweis: "Example",
    bwTitel: "A dental practice wants more implant patients.",
    bwVerlustSatz: "Six months later it has spent:",
    bwP1: "Website and booking flow, built by an agency",
    bwP2: "Agency for concept and management, six months",
    bwP3: "Ad budget over that period",
    bwSummeLabel: "in total",
    bwDannTitel: "Where it hurts",
    bwDann: "The site was finished just as the first ads went live — and didn't match them. It was built back to front.",
    bwHierTitel: "Here",
    bwHier: "It costs you ten minutes. After that your campaign runs for 7 to 30 days.",
    bwPreisLabel: "To start",
    bwBudgetSatz: "What you put into the ad budget per day is up to you — it goes straight to Facebook.",
    bwZusatz: "This machine cost us 25,000 € and a year of work. You get it finished.",
    objTitel: "\u201cI've tried advertising. It did nothing.\u201d",
    objEins: "Usually it wasn't the advertising. It was advertising the whole business instead of one thing.",
    objZwei: "And a page behind the ad that catches nothing — no field, no booking, no list.",
    objDrei: "And nobody measured what one enquiry cost. Without that number every campaign stays a feeling.",
    fragenAnkuendigung: "Four questions. Five minutes.",
    budgetZeile: "You pay the ad budget straight to Facebook, not to us. 10 to 25 € a day is enough to test.",
    feldTitel: "Say it in your own words.",
    feldUnter: "Two or three sentences are plenty. The more concrete, the less I have to guess.",
    urlPlatzhalter: "yourcompany.com",
    urlLabel: "Or just show me your website — I'll read it.",
    bspTitel: "For example:",
    bsp1: "We need care staff",
    bsp2: "We're looking for German-speaking specialists",
    bsp3: "I'm a dentist and I fit implants",
    bsp4: "We install air conditioning",
    bsp5: "We run a beauty salon",
    bsp6: "I sell apartments",
    bsp7: "I want a better job",
    bsp8: "I rent out my event space",
    dashTitel: "This is what it looks like once it runs",
    dashZeitraum: "30 days",
    danachTitel: "And if nothing comes in?",
    danachEins: "After two weeks we go through the numbers together.",
    danachZwei: "If it's too quiet, we swap the hook — we don't raise the budget.",
    danachDrei: "Two or three versions run against each other until one lands.",
    dashHinweis: "Example",
    dashAusgaben: "Spent",
    dashAnfragen: "Enquiries",
    dashProAnfrage: "Per enquiry",
    dashListe: "Who got in touch",
    dashL1Text: "I'm a qualified nurse looking for full-time shift work.",
    dashL2Text: "Question about the third-floor flat — is parking included?",
    dashL3Text: "We need someone for air conditioning, three sites in Timișoara.",
    wasTitel: "What is VersusForge?",
    wasText: "An AI agent that builds your ad, the page behind it, and a list of the people who got in touch. You say in one sentence what you need. It asks back, plans, and shows you first what it would build.",
    wasZwei: "No portal, no commission, no one else's marketplace. What you build stays yours.",
    wasVon: "Built by LuxuryBandit — twelve AI products of our own, running.",
  },
  ro: {
    hookFrage: "Ai site, dar nu-ți vine nicio cerere.",
    hookFrage2: "Aici începe cu reclama — tot ce urmează crește din ea.",
    hookText: "VersusForge scrie reclama, o pornește, construiește pagina din spate — și îți arată într-un dashboard cine te-a contactat.",
    hookKnopf: "Începe acum",
    argTitel: "Construit din față în spate",
    argEins: "Cei mai mulți fac întâi un site sau un magazin — luni întregi până la primul client.",
    argZwei: "Atunci vine gândul: acum trebuie să și fac reclamă.",
    argDrei: "Aici reclama e începutul. Tot ce urmează crește din ea — și îți ține locul portalului.",
    argVier: "Și reclama se face tot aici — din ce oferi tu, nu dintr-un șablon.",
    bwHinweis: "Exemplu",
    bwTitel: "Un cabinet stomatologic vrea mai mulți pacienți pentru implanturi.",
    bwVerlustSatz: "După șase luni a cheltuit:",
    bwP1: "Site și pagină de programări, făcute de o firmă",
    bwP2: "Agenție pentru concept și administrare, șase luni",
    bwP3: "Buget de reclamă în acest timp",
    bwSummeLabel: "în total",
    bwDannTitel: "Ce doare",
    bwDann: "Site-ul a fost gata exact când porneau primele reclame — și nu se potrivea cu ele. A fost construit din spate în față.",
    bwHierTitel: "Aici",
    bwHier: "Pe tine te costă zece minute. Apoi campania ta merge 7 până la 30 de zile.",
    bwPreisLabel: "Ca să pornești",
    bwBudgetSatz: "Cât pui pe zi în buget decizi tu — banii merg direct la Facebook.",
    bwZusatz: "Mașina asta ne-a costat 25.000 € și un an de muncă. Tu o primești gata făcută.",
    objTitel: "\u201eAm încercat cu reclamă. N-a ieșit nimic.\u201d",
    objEins: "De obicei nu reclama a fost problema, ci că promova toată firma în loc de un singur lucru.",
    objZwei: "Și că în spatele reclamei era o pagină care nu prinde nimic — fără formular, fără programare, fără listă.",
    objDrei: "Și nimeni n-a măsurat cât a costat o cerere. Fără cifra asta, orice campanie rămâne o impresie.",
    fragenAnkuendigung: "Patru întrebări. Cinci minute.",
    budgetZeile: "Bugetul de reclamă îl plătești direct la Facebook, nu la noi. Pentru un test ajung 10–25 € pe zi.",
    feldTitel: "Spune cu cuvintele tale.",
    feldUnter: "Două-trei propoziții ajung. Cu cât ești mai concret, cu atât ghicesc mai puțin.",
    urlPlatzhalter: "firmata.ro",
    urlLabel: "Sau arată-mi site-ul tău — îl citesc eu.",
    bspTitel: "De exemplu:",
    bsp1: "Avem nevoie de asistenți medicali",
    bsp2: "Căutăm oameni care vorbesc germană",
    bsp3: "Sunt medic dentist și pun implanturi",
    bsp4: "Montăm aparate de aer condiționat",
    bsp5: "Avem un salon de cosmetică",
    bsp6: "Vând apartamente",
    bsp7: "Vreau un job mai bun",
    bsp8: "Închiriez sala de evenimente",
    dashTitel: "Așa arată când merge",
    dashZeitraum: "30 de zile",
    danachTitel: "Și dacă nu vine nimic?",
    danachEins: "După două săptămâni ne uităm împreună peste cifre.",
    danachZwei: "Dacă vine prea puțin, schimbăm mesajul — nu creștem bugetul.",
    danachDrei: "Două-trei variante merg în paralel până prinde una.",
    dashHinweis: "Exemplu",
    dashAusgaben: "Cheltuit",
    dashAnfragen: "Cereri",
    dashProAnfrage: "Pe cerere",
    dashListe: "Cine te-a contactat",
    dashL1Text: "Sunt asistentă medicală, caut normă întreagă în ture.",
    dashL2Text: "O întrebare despre apartamentul de la etajul trei — parcarea e inclusă?",
    dashL3Text: "Căutăm pe cineva pentru aer condiționat, trei clădiri în Timișoara.",
    wasTitel: "Ce este VersusForge?",
    wasText: "Un agent AI care îți face reclama, pagina din spatele ei și lista oamenilor care te contactează. Spui într-o frază de ce ai nevoie. El întreabă, planifică și îți arată dinainte ce ar construi.",
    wasZwei: "Fără portal, fără comision, fără piața altcuiva. Ce construiești rămâne al tău.",
    wasVon: "Construit de LuxuryBandit — douăsprezece produse AI proprii, în funcțiune.",
  },
};
